-- CREATE TABLE IF NOT EXISTS workspaces
-- (
--     id SERIAL,
--     workspace_name VARCHAR(100) NOT NULL,
--     data_dir VARCHAR(200) NOT NULL,
--     created DATE NOT NULL default CURRENT_DATE,
--     description VARCHAR(10000) DEFAULT NULL,
--     PRIMARY KEY (id)
-- );

-- CREATE TABLE IF NOT EXISTS adata
-- (
--     work_id INT NOT NULL,
--     id SERIAL,
--     adata_name VARCHAR(100) NOT NULL,
--     filename VARCHAR(100) NOT NULL,
--     notes VARCHAR(10000),
--     created DATE NOT NULL default CURRENT_DATE,
--     PRIMARY KEY (work_id, id),
--     FOREIGN KEY (work_id) REFERENCES workspaces (id)
--         ON DELETE CASCADE
--         ON UPDATE CASCADE
-- );
