version: "3.9"
services:
  streamlit:
    container_name: streamlit
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - "80:8501"
    volumes:
      - ./streamlit/.streamlit:/root/.streamlit
      - ./streamlit-volume:/streamlit-volume
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  postgres:
    container_name: postgresql
    build: 
      context: ./postgresql
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data