[server]
headless = true

[client]
toolbarMode = "viewer"

[theme]
primaryColor="#004dcf"
backgroundColor="#181a1e"
secondaryBackgroundColor="linear-gradient(180deg, rgb(5, 39, 103) 0%, #3a0647 70%)"
textColor="#fff"
font="sans serif"