name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: nvidia/cuda:12.2.0-runtime-ubuntu22.04
    steps:
    - name: Run tests
      run: docker-compose -f tests.docker-compose.yml up --build
