name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update docs
      run: python3 docs/generate_docs.py
    - name: Run tests
      run: docker-compose -f tests.docker-compose.yml up --build --abort-on-container-exit
    