name: CI tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Update docs
      run: |
        pip3 install docstring-parser==0.15
        python3 docs/generate_docs.py
    - name: Run tests
      run: |
        docker system prune --force
        docker compose -f tests.docker-compose.yml up --build --abort-on-container-exit